app = "the-ritual-dataset-api" 
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"
  context = "../.."

[build.args]
  VITE_API_URL = "https://the-ritual-dataset-api.fly.dev"

[deploy]
  release_command = "pnpm run prisma:deploy"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
