name: Build & Deploy API (Docker image)

on:
  push:
    branches: [main]
    paths:
      - 'apps/api/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/build-deploy-api.yml'

jobs:
  api:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    concurrency:
      group: deploy-api
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to Fly registry
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth docker

      - name: Compute image tag
        id: meta
        run: echo "tag=registry.fly.io/${{ vars.FLY_APP_API || 'the-ritual-dataset-api' }}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Enable Buildx
        run: docker buildx create --use

      - name: Build & push image
        run: |
          docker buildx build \
            --push \
            --build-arg GIT_SHA=${GITHUB_SHA} \
            --file apps/api/Dockerfile \
            --tag ${{ steps.meta.outputs.tag }} \
            .

      - name: Deploy exact image
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --image ${{ steps.meta.outputs.tag }} -a ${{ vars.FLY_APP_API || 'the-ritual-dataset-api' }}
