name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (with pnpm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack & activate pnpm from package.json
        run: |
          corepack enable
          echo "Using packageManager=$(node -p "require('./package.json').packageManager")"
          corepack prepare $(node -p "require('./package.json').packageManager") --activate
          pnpm -v

      - name: Install (workspace)
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Test
        run: pnpm -r test

      - name: Build (smoke)
        run: pnpm -r build
