name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Install pnpm first (adds PNPM_HOME to PATH)
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      # 2) Then setup Node and enable pnpm caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      # 3) (Optional) sanity print
      - run: pnpm -v

      # 4) Install & run the monorepo scripts
      - name: Install (workspace)
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm -r typecheck

      - name: Test
        run: pnpm -r test

      - name: Build (smoke)
        run: pnpm -r build
