name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    concurrency:
      group: ci-${{ github.ref }}
      cancel-in-progress: true
    env:
      CI: true
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack & activate pnpm
        run: |
          corepack enable
          PM=$(node -p "require('./package.json').packageManager")
          echo "Using $PM"
          corepack prepare "$PM" --activate
          pnpm -v
          which pnpm

      - name: Resolve pnpm store path
        id: pnpm-cache-path
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache-path.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install (workspace)
        run: pnpm install --frozen-lockfile

      # 1) Ensure Prisma client is generated once in the workspace (for API typecheck)
      - name: Prisma generate (API)
        working-directory: apps/api
        run: pnpm run prisma:generate

      # 2) Build API .d.ts for the web to consume
      - name: Build API types
        working-directory: apps/api
        run: pnpm run build:types

      # 3) Typecheck API
      - name: Typecheck API
        working-directory: apps/api
        run: pnpm run typecheck

      # 4) Typecheck Web (now reads ../api/dist-types and won’t pull Prisma)
      - name: Typecheck Web
        working-directory: apps/web
        run: pnpm run typecheck

      - name: Lint
        run: pnpm -r lint

      - name: Format check
        run: pnpm -r format:check

      - name: Test
        run: pnpm -r test:ci

      - name: Build (smoke)
        run: pnpm -r build
