name: Deploy Web (Fly.io)

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - '.github/workflows/deploy-web.yml'

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: deploy-web
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy web
        working-directory: apps/web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only -c apps/web/fly.toml -a the-ritual-dataset-web
